name: NodeJS

on:
  push:

jobs:
  test:
    name: NodeJS test
    runs-on: ubuntu-latest

    steps:
      - run: cat /etc/os-release
      - name: Inspect node installation
        run: |
          set -x
          which node
          node --version
          find /usr/local
